- name: Set up Mysql servers
  hosts: mysql
  become: true
  roles:
    - common-server
    - mysql
    - geerlingguy.mysql
    - forward-server-mail

- name: Set up PosgreSQL server
  hosts: postgres
  become: true
  roles:
    - common-server
    - postgres
    - ANXS.postgresql
    - forward-server-mail

- name: Set up MongoDB server
  hosts: mongodb
  become: true
  roles:
    - common-server
    - mongodb
    - greendayonfire.mongodb
    - forward-server-mail
