- name: Install Python 2
  hosts: mongodb
  become: true
  gather_facts: false
  tasks:
    - raw: "[ -e /usr/bin/python ] || sudo apt-get update -qq && sudo apt-get install -qq python"

- name: Set up MySQL servers
  hosts: mysql
  become: true
  roles:
    - common-server
    - mysql
    - geerlingguy.mysql
    - forward-server-mail

- name: Set up PostgreSQL servers
  hosts: postgres
  become: true
  roles:
    - common-server
    - postgres
    - ANXS.postgresql
    - forward-server-mail

- name: Set up MongoDB servers
  hosts: mongodb
  become: true
  roles:
    - common-server
    - mongodb
    - greendayonfire.mongodb
    - forward-server-mail
