# Note: due to security concerns we prefer using git hashes than ansible versions.

- name: geerlingguy.mysql
  src: https://github.com/geerlingguy/ansible-role-mysql
  version: c71ded56d87c8df606210b59f045ed4c3f1f98ff

# Our fork of security, can be synced when this is merged: https://github.com/geerlingguy/ansible-role-security/pull/16
- name: geerlingguy.security
  src: https://github.com/open-craft/ansible-role-security
  version: origin/jbzdak/notify-mail

- name: kamaln7.swapfile
  src: https://github.com/kamaln7/ansible-swapfile
  version: 8eb0e18d90a7f25b6658fbf56bcba01b84a664fc

# Our fork of pmbauer tarsnap.
# Can be cleared when this is closed: https://github.com/pmbauer/ansible-tarsnap/pull/3
- name: pmbauer.tarsnap
  src: https://github.com/open-craft/ansible-tarsnap
  version: d96b1e69ae6b930e0841d7b025a3070c408a23f4

- name: backup-to-tarsnap
  src: https://github.com/open-craft/ansible-backup-to-tarsnap
  version: origin/master

- name: common-server
  src: https://github.com/open-craft/ansible-common-server
  version: origin/master

- name: configure-apt
  src: https://github.com/open-craft/ansible-configure-apt
  version: origin/master

- name: sanity-checker
  src: https://github.com/open-craft/ansible-sanity-checker/
  version: origin/master

- name: forward-server-mail
  src: https://github.com/open-craft/ansible-forward-server-mail
  version: origin/master

- name: mysql
  src: https://github.com/open-craft/ansible-mysql
  version: origin/master

- name: postgres
  src: https://github.com/open-craft/ansible-postgres
  version: origin/master

- name: ANXS.postgresql
  src: https://github.com/ANXS/postgresql
  version: dda12bcbfa01697f16332adbc1432ea7fe6dfb5f

- name: mongodb
  src: https://github.com/open-craft/ansible-mongodb
  version: origin/master

- name: greendayonfire.mongodb
  src: https://github.com/UnderGreen/ansible-role-mongodb
  version: 084f09a78960f1f4b4b17b24606aca54acd63308
