# Note: due to security concerns we prefer using git hashes than ansible versions.

- name: geerlingguy.mysql
  src: https://github.com/geerlingguy/ansible-role-mysql
  version: 9b3c7c8a0a90cb14f4346b8f69fec94b7314e3c4

# Our fork of security, can be synced when this is merged: https://github.com/geerlingguy/ansible-role-security/pull/16
- name: geerlingguy.security
  src: https://github.com/open-craft/ansible-role-security
  version: '0b495a931c3d9c73732e14811c74bc70635d6c69'

- name: kamaln7.swapfile
  src: https://github.com/kamaln7/ansible-swapfile
  version: 8eb0e18d90a7f25b6658fbf56bcba01b84a664fc

# Our fork of pmbauer tarsnap.
# Can be cleared when this is closed: https://github.com/pmbauer/ansible-tarsnap/pull/3
- name: pmbauer.tarsnap
  src: https://github.com/open-craft/ansible-tarsnap
  version: d96b1e69ae6b930e0841d7b025a3070c408a23f4

- name: backup-to-tarsnap
  src: https://github.com/open-craft/ansible-backup-to-tarsnap
  version: '3d2f6f982ab02112ede9e39e1553b106e5079b87'

- name: common-server
  src: https://github.com/open-craft/ansible-common-server
  version: '8423f76a12f5ade7bd008efffedfee12f9506259'

- name: configure-apt
  src: https://github.com/open-craft/ansible-configure-apt
  version: '97877cadc7927dab043bff70a1e621af3b277b5f'

- name: sanity-checker
  src: https://github.com/open-craft/ansible-sanity-checker/
  version: '5387389cbb640e125595fd57e5ab787504a9537c'

- name: forward-server-mail
  src: https://github.com/open-craft/ansible-forward-server-mail
  version: 'c252ef531802fecace6c0173e647e0a0f13df256'

- name: mysql
  src: https://github.com/open-craft/ansible-mysql
  version: 'd215a7e75bb51b5fe9f8da16cde5c72ef11a5f8f'

- name: postgres
  src: https://github.com/open-craft/ansible-postgres
  version: 'origin/smarnach/postgres'

- name: ANXS.postgresql
  src: https://github.com/ANXS/postgresql
  version: dda12bcbfa01697f16332adbc1432ea7fe6dfb5f

- name: mongodb
  src: https://github.com/open-craft/ansible-mongodb
  version: 'origin/smarnach/mongodb'

- name: greendayonfire.mongodb
  src: https://github.com/UnderGreen/ansible-role-mongodb
  version: 45da87de3d90a764d4689115e86461c6151bcca3
