tarsnap_version: 1.0.37
tarsnap_cache: /var/tarsnap/cache
tarsnap_cron_hour: "*"
tarsnap_tarsnapper_conf: "{{ playbook_dir }}/opencraft-roles/roles/tarsnap/files/conf/tarsnapper.{{ inventory_hostname }}.conf"

FORWARD_MAIL_RELAY_MAIL_TO: 'jacek@opencraft.com'
