tarsnap_version: 1.0.37
tarsnap_cache: /var/tarsnap/cache
tarsnap_cron_hour: "*"

FORWARD_MAIL_RELAY_MAIL_TO: '{{ OPS_EMAIL }}'
COMMON_SERVER_ETCKEEPER_COMMIT_EMAIL: '{{ OPS_EMAIL }}'
security_autoupdate_mail_to: '{{ OPS_EMAIL }}'
