POSTGRES_SERVER_DOMAIN: "{{ inventory_hostname }}"

POSTGRES_SERVER_BACKUP_DIR: '/var/lib/postgres/backup'
TARSNAP_BACKUP_PRE_SCRIPT: "/usr/local/sbin/backup-pre.sh"
TARSNAP_BACKUP_POST_SCRIPT: "/usr/local/sbin/backup-post.sh"
TARSNAP_BACKUP_FOLDERS: "{{ POSTGRES_SERVER_BACKUP_DIR }}"
TARSNAP_ARCHIVE_NAME: "{{ POSTGRES_SERVER_DOMAIN }}"

postgresql_version: 9.3

FORWARD_MAIL_MYDOMAIN: "{{ POSTGRES_SERVER_DOMAIN }}"
UNATTENED_UPGRADES_ERRORS_RELAY_TO: "{{ POSTGRES_SERVER_DOMAIN }}"

SANITY_CHECK_LIVE_PORTS:
  - host: localhost
    port: 5432
    message: "Can't connect to PostgreSQL"

SANITY_CHECK_COMMANDS: []
