MYSQL_SERVER_DOMAIN: "mysql.opencraft.com.local"

# Move this to private once you set a real snitch
MYSQL_SERVER_BACKUP_DIR: '/var/lib/mysql/backup'
TARSNAP_BACKUP_SNITCH: "http://localhost/we-need-to-add-a-snitch-here"
TARSNAP_BACKUP_PRE_SCRIPT: "/usr/local/sbin/backup-pre.sh"
TARSNAP_BACKUP_POST_SCRIPT: "/usr/local/sbin/backup-post.sh"
TARSNAP_BACKUP_FOLDERS: "{{ MYSQL_SERVER_BACKUP_DIR }}"
TARSNAP_ARCHIVE_NAME: "mysql"

mysql_databases:
  - name: "{{ MYSQL_DALITE_DATABASE }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: "{{ MYSQL_DALITE_USER }}"
    host: "%"
    password: "{{ MYSQL_DALITE_PASSWORD }}"
    priv: "{{ MYSQL_DALITE_DATABASE }}.*:ALL"
